2022-04-11 15:52:30,621 (root) Initializing Heralding version 1.0.7
2022-04-11 15:52:30,826 (heralding.honeypot) Using default wordlist file: "/usr/lib/python3.9/site-packages/heralding/wordlist.txt", if you want to customize values please copy this file to the current working directory
2022-04-11 15:52:30,832 (heralding.reporting.file_logger) File logger: Using /var/log/heralding/auth.csv to log authentication attempts in CSV format.
2022-04-11 15:52:30,832 (heralding.reporting.file_logger) File logger: Using /var/log/heralding/session.csv to log unified session data in CSV format.
2022-04-11 15:52:30,833 (heralding.reporting.file_logger) File logger: Using /var/log/heralding/log_session.json to log complete session data in JSON format.
2022-04-11 15:52:36,739 (heralding.honeypot) Found public ip: 34.121.180.85
2022-04-11 15:52:36,740 (heralding.honeypot) Started RDP capability listening on port 3389
2022-04-11 15:52:36,741 (heralding.honeypot) Started Telnet capability listening on port 23
2022-04-11 15:52:36,752 (heralding.honeypot) Started Pop3 capability listening on port 110
2022-04-11 15:52:37,522 (heralding.honeypot) Started Pop3S capability listening on port 995
2022-04-11 15:52:37,523 (heralding.honeypot) Started Http capability listening on port 80
2022-04-11 15:52:37,524 (heralding.honeypot) Started Imap capability listening on port 143
2022-04-11 15:52:37,524 (heralding.honeypot) Started MySQL capability listening on port 3306
2022-04-11 15:52:37,525 (heralding.honeypot) Started Vnc capability listening on port 5900
2022-04-11 15:52:37,525 (heralding.honeypot) Started PostgreSQL capability listening on port 5432
2022-04-11 15:52:37,526 (heralding.honeypot) Started smtp capability listening on port 25
2022-04-11 15:52:40,964 (heralding.honeypot) Started https capability listening on port 443
2022-04-11 15:52:40,965 (heralding.honeypot) Started Socks5 capability listening on port 1080
2022-04-11 15:52:41,821 (heralding.honeypot) Started Imaps capability listening on port 993
2022-04-11 15:52:43,261 (heralding.honeypot) Started SSH capability listening on port 22
2022-04-11 15:52:45,797 (heralding.honeypot) Started smtps capability listening on port 465
2022-04-11 15:52:45,798 (heralding.honeypot) Started ftp capability listening on port 21
2022-04-11 16:52:37,032 (heralding.honeypot) Found public ip: 34.121.180.85
2022-04-11 18:41:32,929 (heralding.honeypot) Found public ip: 34.121.180.85
2022-04-11 20:55:56,455 (heralding.honeypot) Found public ip: 34.121.180.85
2022-04-11 21:12:56,122 (asyncio) Task exception was never retrieved
future: <Task finished name='Task-140' coro=<HandlerBase.handle_session() done, defined at /usr/lib/python3.9/site-packages/heralding/capabilities/handlerbase.py:74> exception=KeyError('user')>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/heralding/capabilities/handlerbase.py", line 86, in handle_session
    await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/usr/lib/python3.9/site-packages/heralding/capabilities/postgresql.py", line 13, in execute_capability
    await self._handle_session(session, reader, writer)
  File "/usr/lib/python3.9/site-packages/heralding/capabilities/postgresql.py", line 38, in _handle_session
    username = login_dict['user']
KeyError: 'user'
2022-04-11 21:59:30,555 (heralding.honeypot) Found public ip: 34.121.180.85
2022-04-11 23:34:58,020 (heralding.honeypot) Found public ip: 34.121.180.85
2022-04-12 01:17:30,875 (heralding.honeypot) Found public ip: 34.121.180.85
2022-04-12 02:51:58,368 (heralding.honeypot) Could not request public ip from ipify, error: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff6261de190>: Failed to establish a new connection: [Errno -3] Try again'))
2022-04-12 03:58:43,415 (heralding.honeypot) Could not request public ip from ipify, error: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff6261dea30>: Failed to establish a new connection: [Errno -3] Try again'))
2022-04-12 06:49:51,608 (heralding.honeypot) Could not request public ip from ipify, error: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff6261de190>: Failed to establish a new connection: [Errno -3] Try again'))
2022-04-12 09:17:55,824 (heralding.honeypot) Could not request public ip from ipify, error: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff62607f2e0>: Failed to establish a new connection: [Errno -3] Try again'))
2022-04-12 11:21:58,259 (heralding.honeypot) Found public ip: 34.121.180.85
