[20042022 16:41:20] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[20042022 16:41:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[20042022 16:42:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 16:43:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 16:44:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 16:45:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 16:46:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 16:47:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 16:48:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 16:49:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 16:50:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 16:51:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 16:52:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 16:53:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 16:54:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 16:55:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 16:56:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 16:57:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 16:58:05] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 16:58:05] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 16:58:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 16:59:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 17:00:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 17:01:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 17:02:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 17:02:40] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[20042022 17:02:40] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[20042022 17:02:41] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[20042022 17:02:42] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[20042022 17:02:42] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[20042022 17:02:43] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[20042022 17:02:43] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[20042022 17:02:44] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[20042022 17:02:44] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[20042022 17:02:45] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[20042022 17:02:45] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[20042022 17:02:46] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[20042022 17:03:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 17:04:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 17:05:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 17:06:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 17:07:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 17:07:43] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[20042022 17:07:48] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[20042022 17:07:48] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[20042022 17:08:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 17:09:18] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[20042022 17:09:22] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[20042022 17:09:22] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[20042022 17:10:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 17:10:39] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 17:10:39] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 17:11:19] ftp /opt/dionaea/lib/dionaea/python/dionaea/ftp.py:235-warning: cmd 'b'AUTH''
[20042022 17:11:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 17:12:11] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 17:12:11] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 17:12:24] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 17:13:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 17:13:32] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 17:13:32] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 17:14:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 17:16:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 17:17:57] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 17:17:57] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 17:17:57] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 17:17:57] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 18:38:27] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 18:38:27] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 18:38:27] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 18:38:27] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 18:38:27] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 18:38:27] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 18:38:27] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 18:38:27] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 18:38:27] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 18:38:27] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 18:38:27] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 18:38:27] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 18:38:27] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 18:38:27] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 18:38:27] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 18:38:27] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 18:38:27] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 18:38:27] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 18:38:27] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[20042022 18:38:51] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[20042022 18:38:51] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[20042022 18:39:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 18:40:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 18:43:06] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 18:45:15] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 18:47:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 18:48:40] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 18:50:15] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 18:51:43] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 18:51:43] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 18:54:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 18:55:40] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 18:58:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 18:59:58] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 18:59:58] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 18:59:58] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 20:17:20] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 20:17:20] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 20:17:20] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 20:17:20] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 20:17:20] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 20:17:20] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 20:17:20] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 20:17:20] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 20:17:20] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 20:17:20] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 20:17:20] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 20:17:20] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 20:17:20] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 20:17:20] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[20042022 20:17:26] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[20042022 20:17:26] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[20042022 20:18:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 20:19:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 20:20:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 20:23:40] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 20:30:08] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 20:39:23] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 20:48:59] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 20:51:12] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 20:51:12] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 21:48:42] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 21:48:42] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 21:48:42] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 21:48:42] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 21:48:42] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[20042022 21:48:46] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[20042022 21:48:46] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[20042022 21:49:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 21:50:50] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 21:53:55] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 21:53:55] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 21:55:40] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 21:57:15] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 21:58:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 21:59:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 22:00:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 22:01:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 22:02:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 22:03:46] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 22:03:46] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 22:03:46] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 22:03:46] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 22:03:46] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 22:03:46] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 22:03:46] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 22:12:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 22:12:35] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
