[01052022 19:30:29] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[01052022 19:30:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[01052022 19:31:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:32:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:33:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:34:19] SMB /opt/dionaea/lib/dionaea/python/dionaea/smb/smb.py:836-warning: epmapper - not enough data
[01052022 19:34:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:35:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:36:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:37:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:38:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:39:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:40:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:41:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:42:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:43:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:44:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:45:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:46:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:47:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:48:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:49:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:50:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:51:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:52:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:53:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:54:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:55:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 19:55:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 19:55:14] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:55:14] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:55:14] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:55:14] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:55:14] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:55:14] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:55:14] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:55:14] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 19:55:14] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 22:45:07] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 22:45:07] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 22:45:07] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 22:45:07] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 22:45:07] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 22:45:07] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 22:45:07] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 22:45:07] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 22:45:07] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 22:45:07] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 22:45:07] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 22:45:07] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 22:45:07] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 22:45:07] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 22:45:07] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
