[05042022 16:41:20] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[05042022 16:41:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[05042022 16:42:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 16:43:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 16:43:30] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[05042022 16:43:30] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[05042022 16:44:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 16:44:59] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[05042022 16:45:23] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 16:46:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 16:46:26] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[05042022 16:47:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 16:48:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 16:49:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 16:50:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 16:51:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 16:52:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 16:53:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 16:54:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 16:54:30] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[05042022 16:54:34] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[05042022 16:54:34] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[05042022 16:55:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 16:56:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 16:57:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 16:58:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 16:59:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:00:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:01:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:02:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:03:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:04:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:05:01] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[05042022 17:05:04] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[05042022 17:05:04] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[05042022 17:05:54] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[05042022 17:05:57] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[05042022 17:05:57] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[05042022 17:06:02] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[05042022 17:06:02] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[05042022 17:06:27] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[05042022 17:06:27] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[05042022 17:06:58] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:07:58] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:08:58] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:09:58] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:10:58] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:11:58] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:12:57] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:13:58] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:14:58] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:15:58] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:16:58] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:17:46] SMB /opt/dionaea/lib/dionaea/python/dionaea/smb/smb.py:127-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[05042022 17:17:46] SMB /opt/dionaea/lib/dionaea/python/dionaea/smb/smb.py:157-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[05042022 17:17:58] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:18:58] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:19:58] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:20:58] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:21:56] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:22:58] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:23:57] ftp /opt/dionaea/lib/dionaea/python/dionaea/ftp.py:235-warning: cmd 'b'AUTH''
[05042022 17:23:57] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:24:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:24:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:24:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 17:24:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:03:49] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[05042022 19:03:49] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[05042022 19:03:49] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[05042022 19:03:49] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[05042022 19:03:49] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[05042022 19:03:49] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[05042022 19:03:49] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[05042022 19:03:49] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[05042022 19:03:49] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[05042022 19:03:49] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[05042022 19:03:49] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[05042022 19:03:54] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[05042022 19:03:54] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[05042022 19:06:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:10:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:11:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:13:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:14:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:15:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:16:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:17:50] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:19:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:20:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:21:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:22:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:24:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:25:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:26:40] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:29:51] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:31:10] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[05042022 19:31:10] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[05042022 19:31:10] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[05042022 19:31:10] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[05042022 19:31:10] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[05042022 19:31:10] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[05042022 19:31:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:31:10] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[05042022 19:31:10] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[05042022 19:40:22] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:49:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:49:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 19:49:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 20:54:44] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[05042022 20:57:59] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[05042022 20:57:59] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[05042022 20:59:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[05042022 21:00:19] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
