2022-04-05 16:41:28,367 Config file found!
2022-04-05 16:41:28,372 Starting Conpot using template: /usr/lib/python3.9/site-packages/conpot/templates/guardian_ast
2022-04-05 16:41:28,372 Starting Conpot using configuration found in: /etc/conpot/conpot.cfg
2022-04-05 16:41:28,385 Serving tar:///usr/lib/python3.9/site-packages/conpot/data.tar as file system. File uploads will be kept at : /tmp/conpot
2022-04-05 16:41:28,387 Opening path /tmp/conpot for persistent storage of files.
2022-04-05 16:41:28,391 Initializing Virtual File System at /tmp/conpot/__conpot__162grm1k. Source specified : tar:///usr/lib/python3.9/site-packages/conpot/data.tar
 Please wait while the system copies all specified files
2022-04-05 16:41:28,639 Fetched 34.121.180.85 as external ip.
2022-04-05 16:41:28,642 Conpot GuardianAST initialized
2022-04-05 16:41:28,643 Found and enabled guardian_ast protocol.
2022-04-05 16:41:28,644 No proxy template found. Service will remain unconfigured/stopped.
2022-04-05 16:41:28,644 GuardianAST server started on: ('0.0.0.0', 10001)
2022-04-05 20:54:43,402 New guardian_ast session from 94.232.41.210 (a0b1b1a8-33c5-4cc0-bd56-d8a45745a641)
2022-04-05 20:54:43,580 New GuardianAST connection from 94.232.41.210:65438. (a0b1b1a8-33c5-4cc0-bd56-d8a45745a641)
2022-04-05 20:54:43,631 Non ^A command attempt 94.232.41.210:65438. (a0b1b1a8-33c5-4cc0-bd56-d8a45745a641)
2022-04-05 20:54:43,632 GuardianAST client disconnected 94.232.41.210:65438. (a0b1b1a8-33c5-4cc0-bd56-d8a45745a641)
2022-04-05 20:54:43,632 New guardian_ast session from 162.142.125.7 (cc168191-67cc-4ea9-b8c4-de34d437aa6b)
2022-04-05 20:54:43,632 New GuardianAST connection from 162.142.125.7:51276. (cc168191-67cc-4ea9-b8c4-de34d437aa6b)
2022-04-05 20:54:43,633 I20100 command attempt 162.142.125.7:51276. (cc168191-67cc-4ea9-b8c4-de34d437aa6b)
2022-04-05 20:54:43,633 Unknown Error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/conpot/protocols/guardian_ast/guardian_ast_server.py", line 497, in handle
    sock.send(str_to_bytes(response))
  File "/usr/lib/python3.9/site-packages/gevent/_socketcommon.py", line 722, in send
    return self._sock.send(data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer
2022-04-05 20:54:44,049 GuardianAST client disconnected 162.142.125.7:51276. (cc168191-67cc-4ea9-b8c4-de34d437aa6b)
2022-04-05 20:54:44,049 New GuardianAST connection from 162.142.125.7:50984. (cc168191-67cc-4ea9-b8c4-de34d437aa6b)
2022-04-05 20:54:44,050 Unknown Error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/conpot/protocols/guardian_ast/guardian_ast_server.py", line 322, in handle
    request = sock.recv(4096)
  File "/usr/lib/python3.9/site-packages/gevent/_socketcommon.py", line 657, in recv
    return self._sock.recv(*args)
ConnectionResetError: [Errno 104] Connection reset by peer
2022-04-05 20:54:44,051 GuardianAST client disconnected 162.142.125.7:50984. (cc168191-67cc-4ea9-b8c4-de34d437aa6b)
2022-04-05 20:54:44,051 New GuardianAST connection from 162.142.125.7:45944. (cc168191-67cc-4ea9-b8c4-de34d437aa6b)
2022-04-05 20:54:44,052 Non ^A command attempt 162.142.125.7:45944. (cc168191-67cc-4ea9-b8c4-de34d437aa6b)
2022-04-05 20:54:44,052 GuardianAST client disconnected 162.142.125.7:45944. (cc168191-67cc-4ea9-b8c4-de34d437aa6b)
2022-04-05 20:54:44,056 New GuardianAST connection from 162.142.125.7:58424. (cc168191-67cc-4ea9-b8c4-de34d437aa6b)
2022-04-05 20:54:44,057 Non ^A command attempt 162.142.125.7:58424. (cc168191-67cc-4ea9-b8c4-de34d437aa6b)
2022-04-05 20:54:44,057 GuardianAST client disconnected 162.142.125.7:58424. (cc168191-67cc-4ea9-b8c4-de34d437aa6b)
2022-04-05 20:54:44,058 New GuardianAST connection from 162.142.125.7:35590. (cc168191-67cc-4ea9-b8c4-de34d437aa6b)
2022-04-05 20:54:44,058 Unknown Error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/conpot/protocols/guardian_ast/guardian_ast_server.py", line 322, in handle
    request = sock.recv(4096)
  File "/usr/lib/python3.9/site-packages/gevent/_socketcommon.py", line 657, in recv
    return self._sock.recv(*args)
ConnectionResetError: [Errno 104] Connection reset by peer
2022-04-05 20:54:44,059 GuardianAST client disconnected 162.142.125.7:35590. (cc168191-67cc-4ea9-b8c4-de34d437aa6b)
2022-04-05 20:55:14,125 Session timed out: a0b1b1a8-33c5-4cc0-bd56-d8a45745a641
2022-04-05 20:55:17,327 Session timed out: cc168191-67cc-4ea9-b8c4-de34d437aa6b
2022-04-06 00:49:49,597 New guardian_ast session from 54.153.22.72 (c59186d7-1129-412e-a646-a84c76ac5485)
2022-04-06 00:49:49,741 New GuardianAST connection from 54.153.22.72:35662. (c59186d7-1129-412e-a646-a84c76ac5485)
2022-04-06 00:49:49,831 I20100 command attempt 54.153.22.72:35662. (c59186d7-1129-412e-a646-a84c76ac5485)
2022-04-06 00:50:00,095 GuardianAST client disconnected 54.153.22.72:35662. (c59186d7-1129-412e-a646-a84c76ac5485)
2022-04-06 00:50:31,989 Session timed out: c59186d7-1129-412e-a646-a84c76ac5485
2022-04-06 01:28:04,859 New guardian_ast session from 54.153.55.79 (6a9e3dd5-afdf-4bf5-92cd-3e87a47e48e1)
2022-04-06 01:28:08,179 New GuardianAST connection from 54.153.55.79:36396. (6a9e3dd5-afdf-4bf5-92cd-3e87a47e48e1)
2022-04-06 01:28:13,275 Invalid command attempt 54.153.55.79:36396. (6a9e3dd5-afdf-4bf5-92cd-3e87a47e48e1)
2022-04-06 01:28:17,086 GuardianAST client disconnected 54.153.55.79:36396. (6a9e3dd5-afdf-4bf5-92cd-3e87a47e48e1)
2022-04-06 01:28:53,355 Session timed out: 6a9e3dd5-afdf-4bf5-92cd-3e87a47e48e1
