2022-04-19 16:25:49,952 Config file found!
2022-04-19 16:25:49,961 Starting Conpot using template: /usr/lib/python3.9/site-packages/conpot/templates/guardian_ast
2022-04-19 16:25:49,961 Starting Conpot using configuration found in: /etc/conpot/conpot.cfg
2022-04-19 16:25:49,975 Serving tar:///usr/lib/python3.9/site-packages/conpot/data.tar as file system. File uploads will be kept at : /tmp/conpot
2022-04-19 16:25:49,976 Opening path /tmp/conpot for persistent storage of files.
2022-04-19 16:25:49,978 Initializing Virtual File System at /tmp/conpot/__conpot__zgxiwelf. Source specified : tar:///usr/lib/python3.9/site-packages/conpot/data.tar
 Please wait while the system copies all specified files
2022-04-19 16:25:50,223 Fetched 34.121.180.85 as external ip.
2022-04-19 16:25:50,226 Conpot GuardianAST initialized
2022-04-19 16:25:50,227 Found and enabled guardian_ast protocol.
2022-04-19 16:25:50,228 No proxy template found. Service will remain unconfigured/stopped.
2022-04-19 16:25:50,229 GuardianAST server started on: ('0.0.0.0', 10001)
2022-04-19 17:55:24,557 New guardian_ast session from 162.142.125.7 (4a92c1fd-66f2-43b7-baf0-8297787266c2)
2022-04-19 18:05:51,397 New GuardianAST connection from 162.142.125.7:51656. (4a92c1fd-66f2-43b7-baf0-8297787266c2)
2022-04-19 18:30:28,772 I20100 command attempt 162.142.125.7:51656. (4a92c1fd-66f2-43b7-baf0-8297787266c2)
2022-04-19 18:44:57,375 Unknown Error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/conpot/protocols/guardian_ast/guardian_ast_server.py", line 497, in handle
    sock.send(str_to_bytes(response))
  File "/usr/lib/python3.9/site-packages/gevent/_socketcommon.py", line 722, in send
    return self._sock.send(data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer
2022-04-19 19:26:43,902 GuardianAST client disconnected 162.142.125.7:51656. (4a92c1fd-66f2-43b7-baf0-8297787266c2)
2022-04-19 19:26:43,969 New GuardianAST connection from 162.142.125.7:42380. (4a92c1fd-66f2-43b7-baf0-8297787266c2)
2022-04-19 19:26:44,034 Unknown Error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/conpot/protocols/guardian_ast/guardian_ast_server.py", line 322, in handle
    request = sock.recv(4096)
  File "/usr/lib/python3.9/site-packages/gevent/_socketcommon.py", line 657, in recv
    return self._sock.recv(*args)
ConnectionResetError: [Errno 104] Connection reset by peer
2022-04-19 19:26:44,096 GuardianAST client disconnected 162.142.125.7:42380. (4a92c1fd-66f2-43b7-baf0-8297787266c2)
2022-04-19 19:26:44,096 New GuardianAST connection from 162.142.125.7:34066. (4a92c1fd-66f2-43b7-baf0-8297787266c2)
2022-04-19 19:26:44,097 Non ^A command attempt 162.142.125.7:34066. (4a92c1fd-66f2-43b7-baf0-8297787266c2)
2022-04-19 19:26:44,097 GuardianAST client disconnected 162.142.125.7:34066. (4a92c1fd-66f2-43b7-baf0-8297787266c2)
2022-04-19 19:26:44,097 New GuardianAST connection from 162.142.125.7:39146. (4a92c1fd-66f2-43b7-baf0-8297787266c2)
2022-04-19 19:26:44,098 Non ^A command attempt 162.142.125.7:39146. (4a92c1fd-66f2-43b7-baf0-8297787266c2)
2022-04-19 19:26:44,098 GuardianAST client disconnected 162.142.125.7:39146. (4a92c1fd-66f2-43b7-baf0-8297787266c2)
2022-04-19 19:26:44,098 New GuardianAST connection from 162.142.125.7:46634. (4a92c1fd-66f2-43b7-baf0-8297787266c2)
2022-04-19 19:26:44,099 Unknown Error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/conpot/protocols/guardian_ast/guardian_ast_server.py", line 322, in handle
    request = sock.recv(4096)
  File "/usr/lib/python3.9/site-packages/gevent/_socketcommon.py", line 657, in recv
    return self._sock.recv(*args)
ConnectionResetError: [Errno 104] Connection reset by peer
2022-04-19 19:26:44,099 GuardianAST client disconnected 162.142.125.7:46634. (4a92c1fd-66f2-43b7-baf0-8297787266c2)
2022-04-19 19:27:15,195 Session timed out: 4a92c1fd-66f2-43b7-baf0-8297787266c2
