[*] INFO:	Build size map
[*] INFO:	(800, 600) -> /opt/rdpy/3
[*] INFO:	
2022-04-05T17:06:36.147062Z,Connection from 89.248.165.205:41623
[*] ERROR:	Error during read <class 'rdpy.protocol.rdp.x224.X224DataHeader'>::messageType
[*] INFO:	
2022-04-05T17:07:34.623501Z,Connection from 89.248.165.205:47040
[*] ERROR:	Error during read <class 'rdpy.protocol.rdp.x224.X224DataHeader'>::messageType
[*] INFO:	
2022-04-05T17:08:52.654452Z,Connection from 89.248.165.205:57502
[*] ERROR:	Error during read <class 'rdpy.protocol.rdp.x224.X224DataHeader'>::messageType
[*] INFO:	
2022-04-05T17:11:03.050013Z,Connection from 89.248.165.205:18303
[*] ERROR:	Error during read <class 'rdpy.protocol.rdp.x224.X224DataHeader'>::messageType
[*] INFO:	
2022-04-05T17:15:09.282550Z,Connection from 89.248.165.205:10088
[*] ERROR:	Error during read <class 'rdpy.protocol.rdp.x224.X224DataHeader'>::messageType
[*] INFO:	
2022-04-05T17:15:49.011242Z,Connection from 89.248.165.205:18127
[*] INFO:	
2022-04-05T17:15:49.182497Z,Connection from 89.248.165.205:18200
[*] INFO:	
2022-04-05T17:15:49.216909Z,Connection from 89.248.165.205:18229
[*] ERROR:	Error during read <class 'rdpy.protocol.rdp.x224.X224DataHeader'>::messageType
[*] ERROR:	Error during read <class 'rdpy.protocol.rdp.x224.X224DataHeader'>::messageType
[*] ERROR:	Error during read <class 'rdpy.protocol.rdp.x224.X224DataHeader'>::messageType
[*] INFO:	
2022-04-05T17:15:51.112548Z,Connection from 89.248.165.205:18802
[*] ERROR:	Error during read <class 'rdpy.protocol.rdp.x224.X224DataHeader'>::messageType
[*] INFO:	
2022-04-05T19:03:48.918753Z,Connection from 31.43.185.8:62566
[*] INFO:	
2022-04-05T19:03:49.330931Z,Connection from 34.86.35.13:55909
[*] INFO:	
2022-04-05T19:19:04.771907Z,Connection from 94.232.41.206:65497
[*] INFO:	
2022-04-05T20:54:43.600135Z,Connection from 140.238.121.81:43489
[*] INFO:	
2022-04-05T20:54:44.090231Z,Connection from 94.232.41.206:65462
[*] INFO:	
2022-04-05T20:54:44.398171Z,Connection from 89.248.165.205:46219
[*] INFO:	
2022-04-05T20:54:44.571562Z,Connection from 89.248.165.205:51627
[*] INFO:	
2022-04-05T20:54:44.603113Z,Connection from 89.248.165.205:3005
[*] INFO:	
2022-04-05T20:54:44.644542Z,Connection from 89.248.165.205:22632
[*] INFO:	
2022-04-05T20:54:44.831888Z,Connection from 89.248.165.205:14662
[*] INFO:	
2022-04-05T20:54:44.887949Z,Connection from 89.248.165.205:22696
[*] INFO:	
2022-04-05T20:54:44.968761Z,Connection from 89.248.165.205:22747
[*] INFO:	
2022-04-05T20:54:45.242770Z,Connection from 89.248.165.205:22748
[*] INFO:	
2022-04-05T20:54:45.285271Z,Connection from 89.248.165.205:23343
[*] ERROR:	Error during read <class 'rdpy.protocol.rdp.x224.X224DataHeader'>::messageType
[*] ERROR:	Error during read <class 'rdpy.protocol.rdp.x224.X224DataHeader'>::messageType
[*] ERROR:	Error during read <class 'rdpy.protocol.rdp.x224.X224DataHeader'>::messageType
[*] ERROR:	Error during read <class 'rdpy.protocol.rdp.x224.X224DataHeader'>::messageType
[*] ERROR:	Error during read <class 'rdpy.protocol.rdp.x224.X224DataHeader'>::messageType
[*] ERROR:	Error during read <class 'rdpy.protocol.rdp.x224.X224DataHeader'>::messageType
[*] ERROR:	Error during read <class 'rdpy.protocol.rdp.x224.X224DataHeader'>::messageType
[*] ERROR:	Error during read <class 'rdpy.protocol.rdp.x224.X224DataHeader'>::messageType
[*] ERROR:	Error during read <class 'rdpy.protocol.rdp.x224.X224DataHeader'>::messageType
[*] INFO:	
2022-04-05T21:09:47.762128Z,Connection from 31.43.185.8:61525
[*] INFO:	
2022-04-05T21:09:54.844200Z,Connection from 194.8.147.18:3691
[*] INFO:	
2022-04-06T00:49:04.261758Z,Connection from 43.249.31.28:8899
[*] INFO:	
2022-04-06T00:49:04.579079Z,Connection from 43.249.31.28:9291
